---
name: etcd-acceptance

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

releases:
- name: etcd-acceptance
  version: latest
- name: bosh-dns
  version: "1.7.0"
  url: "https://bosh.io/d/github.com/cloudfoundry/bosh-dns-release?v=1.7.0"
  sha1: "3046a07083751ae7740bbf7a25a1df6162628469"

features:
  use_dns_addresses: true

addons:
- name: bosh-dns
  include:
    stemcells:
    - os: ubuntu-xenial
  jobs:
  - name: bosh-dns
    release: bosh-dns
    properties:
      api:
        server:
          tls: ((/dns_api_server_tls))
        client:
          tls: ((/dns_api_client_tls))
      cache:
        enabled: true
      health:
        enabled: true
        server:
          tls: ((/dns_healthcheck_server_tls))
        client:
          tls: ((/dns_healthcheck_client_tls))


instance_groups:
- name: etcd-acceptance
  lifecycle: errand
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: read-availability-during-recreate
    release: etcd-acceptance
    consumes:
      etcd: {from: etcd, deployment: ((etcd-deployment-name))}
      turbulence: {from: api, deployment: turbulence}
    properties:
      deployment_name: ((etcd-deployment-name))
      director_ca: ((director-ca))
      director_client_secret: ((director-client-secret))
      director_url: ((director-url))
      uaa_url: ((uaa-url))
  - name: read-availability-during-network-partition
    release: etcd-acceptance
    consumes:
      etcd: {from: etcd, deployment: ((etcd-deployment-name))}
      turbulence: {from: api, deployment: turbulence}
    properties:
      deployment_name: ((etcd-deployment-name))
      director_ca: ((director-ca))
      director_client_secret: ((director-client-secret))
      director_url: ((director-url))
      uaa_url: ((uaa-url))
  - name: read-availability-during-total-network-partition
    release: etcd-acceptance
    consumes:
      etcd: {from: etcd, deployment: ((etcd-deployment-name))}
      turbulence: {from: api, deployment: turbulence}
    properties:
      deployment_name: ((etcd-deployment-name))
      director_ca: ((director-ca))
      director_client_secret: ((director-client-secret))
      director_url: ((director-url))
      uaa_url: ((uaa-url))
  - name: read-availability-during-network-partition-granular
    release: etcd-acceptance
    consumes:
      etcd: {from: etcd, deployment: ((etcd-deployment-name))}
      turbulence: {from: api, deployment: turbulence}
    properties:
      deployment_name: ((etcd-deployment-name))
      director_ca: ((director-ca))
      director_client_secret: ((director-client-secret))
      director_url: ((director-url))
      uaa_url: ((uaa-url))

update:
  serial: true
  canaries: 0
  max_in_flight: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

variables:
- name: /dns_healthcheck_tls_ca
  opsname: global_dns_healthcheck_tls_ca
  type: certificate
  options:
    is_ca: true
    common_name: dns-healthcheck-tls-ca

- name: /dns_healthcheck_server_tls
  opsname: global_dns_healthcheck_server_tls
  type: certificate
  options:
    ca: /dns_healthcheck_tls_ca
    common_name: health.bosh-dns
    extended_key_usage:
    - server_auth

- name: /dns_healthcheck_client_tls
  opsname: global_dns_healthcheck_client_tls
  type: certificate
  options:
    ca: /dns_healthcheck_tls_ca
    common_name: health.bosh-dns
    extended_key_usage:
    - client_auth

- name: /dns_api_tls_ca
  opsname: global_dns_api_tls_ca
  type: certificate
  options:
    is_ca: true
    common_name: dns-api-tls-ca

- name: /dns_api_server_tls
  opsname: global_dns_api_server_tls
  type: certificate
  options:
    ca: /dns_api_tls_ca
    common_name: api.bosh-dns
    extended_key_usage:
    - server_auth

- name: /dns_api_client_tls
  opsname: global_dns_api_client_tls
  type: certificate
  options:
    ca: /dns_api_tls_ca
    common_name: api.bosh-dns
    extended_key_usage:
    - client_auth
