---
name: etcd-acceptance

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: etcd-acceptance
  version: latest
- name: bosh-dns
  version: latest

features:
  use_dns_addresses: true

addons:
- name: bosh-dns
  include:
    stemcells:
    - os: ubuntu-trusty
  jobs:
  - name: bosh-dns
    release: bosh-dns
    properties:
      cache:
        enabled: true

instance_groups:
- name: etcd-acceptance
  lifecycle: errand
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: read-availability-during-recreate
    release: etcd-acceptance
    consumes:
      etcd: {from: etcd, deployment: ((etcd-deployment-name))}
      turbulence: {from: api, deployment: turbulence}
    properties:
      deployment_name: ((etcd-deployment-name))
      director_ca: ((director-ca))
      director_client_secret: ((director-client-secret))
      director_url: ((director-url))
      uaa_url: ((uaa-url))
  - name: read-availability-during-network-partition
    release: etcd-acceptance
    consumes:
      etcd: {from: etcd, deployment: ((etcd-deployment-name))}
      turbulence: {from: api, deployment: turbulence}
    properties:
      deployment_name: ((etcd-deployment-name))
      director_ca: ((director-ca))
      director_client_secret: ((director-client-secret))
      director_url: ((director-url))
      uaa_url: ((uaa-url))
  - name: read-availability-during-total-network-partition
    release: etcd-acceptance
    consumes:
      etcd: {from: etcd, deployment: ((etcd-deployment-name))}
      turbulence: {from: api, deployment: turbulence}
    properties:
      deployment_name: ((etcd-deployment-name))
      director_ca: ((director-ca))
      director_client_secret: ((director-client-secret))
      director_url: ((director-url))
      uaa_url: ((uaa-url))
  - name: read-availability-during-network-partition-granular
    release: etcd-acceptance
    consumes:
      etcd: {from: etcd, deployment: ((etcd-deployment-name))}
      turbulence: {from: api, deployment: turbulence}
    properties:
      deployment_name: ((etcd-deployment-name))
      director_ca: ((director-ca))
      director_client_secret: ((director-client-secret))
      director_url: ((director-url))
      uaa_url: ((uaa-url))

update:
  serial: true
  canaries: 0
  max_in_flight: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
